name: E2E environment

on:
  push:

jobs:
  e2e:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - run: sh -ci "$(curl -fsSL https://raw.githubusercontent.com/onflow/flow-cli/master/install.sh)"

      - run: /root/.local/bin/flow emulator -f flow-emulator.json --chain-id mainnet --rpc-host access.mainnet.nodes.onflow.org:9000 --start-block-height 101908562 &
      - run: sleep 4
      - run: /root/.local/bin/flow blocks get 101908562 --host localhost:3569 --include transactions

